web:
  image: ${BUILD_IMAGE}
  user: "${CURRENT_UID}" # Set in docker.sh
  volumes:
    - "./app:/src/app"
    - "./node_modules/:/src/app/node_modules"
    - "./package.json:/src/app/package.json"
    - "./yarn.lock:/src/app/yarn.lock"
    - "./docker/startup.sh:/src/app/startup.sh"
  ports:
      - "${PORTS}"
  working_dir: /src/app
  command: "sh -c ./startup.sh"
  environment:
    - CURRENT_UID=${CURRENT_UID}
