web:
  image: ${BUILD_IMAGE}
  user: "${USERID}:${GROUPID}"
  volumes:
    - "./app:/src/app"
    - "./node_modules/:/src/app/node_modules"
    - "./package.json:/src/app/package.json"
    - "./docker/startup.sh:/src/app/startup.sh"
  ports:
      - "3000:3000"
  working_dir: /src/app
