version: '3.5'
services:
  web:
    restart: always
    container_name: "${APP_NAME}_prod_web"
    environment:
      - APP_ENV=production
      - VIRTUAL_HOST=bowling.sharetransition.com
      - LETSENCRYPT_HOST=bowling.sharetransition.com
      - LETSENCRYPT_EMAIL=micke@sharetransition.com

networks:
  default:
    external:
      name: nginx-proxy
